#!/bin/bash
IMGID=f-go:latest
CNAME="fgofe"

CODEPATH=$FDOCKER/f-go/examples/frontend/code

# CMDS="cd /home/dev/code; go build -o main; ./main;"
CMDS="cd /home/dev/code; gin -p 20080 -a 30080 run server.go"

docker run --name $CNAME -p 20080:20080 -v $CODEPATH:/home/dev/code --user="dev" -it $IMGID bash --login -c "$CMDS"
