version: '2'
services:
  nginx:
    build:
      context: ./nginx
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    ports:
      - 80:80
  node1:
    build:
      context: ./node
    ports:
      - 8081:8080
  node2:
    build:
      context: ./node
    ports:
      - 8082:8080
  node3:
    build:
      context: ./node
    ports:
      - 8083:8080
