#!/bin/bash
IMGNAME=alpine
IMGTAG=3.4
IMGID=$IMGNAME:$IMGTAG

echo "*********************************** START " $IMGID
docker rmi $IMGID
echo "*********************************** RUNNING " $IMGID
cd $FDOCKER/$IMGNAME/$IMGTAG
echo $IMGID " " $PWD

docker pull $IMGID

echo "*********************************** DONE " $IMGID
