#!/bin/sh
# USAGE: init [dev | prod]

source ./clean

# Clone Repo
cd fe
git clone https://github.com/freiny/dockerpack-fe-nodejs.git
mv ./dockerpack-fe-nodejs repo
cd ..

docker-compose --file $1.yml up
