version: '2'
services:

  rp1:
    build:
      context: ./rp
      dockerfile: prod.Dockerfile

    links:
      - fe1:fe1
      - fe2:fe2
      - fe3:fe3
    ports:
      - 80:80

  fe1:
    build:
      context: ./fe
      dockerfile: prod.Dockerfile
    ports:
      - 10001:10000

  fe2:
    build:
      context: ./fe
      dockerfile: prod.Dockerfile
    ports:
      - 10002:10000

  fe3:
    build:
      context: ./fe
      dockerfile: prod.Dockerfile
    ports:
      - 10003:10000
