#!/bin/bash
IMGNAME=f-go
IMGTAG=3
IMGID=$IMGNAME:$IMGTAG

BASENAME=f-go
BASETAG=0
BASEID=$BASENAME:$BASETAG

echo "*********************************** START " $IMGID
docker rmi $IMGID
$FDOCKER/$BASENAME/$BASETAG/init
echo "*********************************** RUNNING " $IMGID
cd $FDOCKER/$IMGNAME/$IMGTAG
echo $IMGID " " $PWD

CMDS="go get github.com/codegangsta/gin"

docker run -t --user="dev" --name cname $BASEID bash --login -c "$CMDS"

docker commit cname iname
docker rm cname

docker tag iname $IMGID
docker rmi iname

echo "*********************************** DONE " $IMGID
