#!/bin/bash
CODEPATH=$FDOCKER/f-node/examples/backend/code
HOMEPATH=/home/dev
docker run --name fNodeBE -p 10080:10080 -v $CODEPATH:$HOMEPATH/code --user="dev" -it f-node:1 bash --login -c "cd $HOMEPATH/code; npm install; npm start"
