#!/bin/sh

case $1 in

	dev)
 		cd /src
		npm install
		npm start &
		ps -ef

		while inotifywait -e modify /src; do
			killall -9 node
			npm start &
			ps ef
		done
	;;

	prod)
		cd /src
		npm install
		npm start
	;;

	*)
		echo "Init Container: init [dev | prod]"

esac
