#!/bin/bash
################################
# this version most likely not working
# use v3+ or latest
################################

IMGNAME=f-go
IMGTAG=2
IMGID=$IMGNAME:$IMGTAG
echo "*********************************** START " $IMGID

BASENAME=f-go
BASETAG=0
BASEID=$BASENAME:$BASETAG

docker rmi $IMGID

cd $FDOCKER/$BASENAME/$BASETAG
./init
cd $FDOCKER/$IMGNAME/$IMGTAG

CMDS="
apk add --update git go
GOPATH=/home/dev/go
go get github.com/codegangsta/gin
"

docker run --user="dev" --name cname $BASEID bash -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $IMGID
docker rmi iname
echo "*********************************** DONE " $IMGID
