#!/bin/bash
#source $DOCKER_SCRIPTS/$imgName/$imgVer/clean
docker run -it --user=$userName -p $DOCKER_BACKEND_PORT:$DOCKER_BACKEND_PORT -v $userHome:/home/$userName --name $cName $imgName:$imgVer bash --login
