version: '2'
services:

  be1:
    build:
      context: ./be
      dockerfile: dev.Dockerfile
    # links:
    #   - ch1:ch1
    ports:
      - 24001:24000
    # network_mode: "bridge"
    volumes:
      - ./be/repo/src:/src
      - ./be/home:/home
