version: '2'
services:

  rp1:
    build:
      context: ./rp
      dockerfile: dev.Dockerfile
    links:
      - fe1:fe1
      - be1:be1
    ports:
      - 3000:3000
      - 4000:4000

  fe1:
    build:
      context: ./fe
      dockerfile: dev.Dockerfile
    ports:
      - 13001:13000
    volumes:
      - ./fe/repo/src:/src
      - ./fe/home:/home

  be1:
    build:
      context: ./be
      dockerfile: dev.Dockerfile
    ports:
      - 24001:24000
    volumes:
      - ./be/repo/src:/src
      - ./be/home:/home
