#!/bin/bash
ITAG=f-alpine:1
docker rmi $ITAG

BASE=alpine:3.4
docker pull $BASE

CMDS="apk add --update bash nano"

docker run --name cname $BASE sh -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $ITAG
docker rmi iname
