#!/bin/bash
IMGNAME=f-alpine
IMGTAG=1
IMGID=$IMGNAME:$IMGTAG

BASENAME=alpine
BASETAG=3.4
BASEID=$BASENAME:$BASETAG

echo "*********************************** START " $IMGID
docker rmi $IMGID
$FDOCKER/$BASENAME/$BASETAG/init
echo "*********************************** RUNNING " $IMGID
cd $FDOCKER/$IMGNAME/$IMGTAG
echo $IMGID " " $PWD

CMDS="apk add --update bash nano"

docker run --name cname $BASEID sh -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $IMGID
docker rmi iname

echo "*********************************** DONE " $IMGID
