version: '2'
services:

  rp1:
    build:
      context: ./rp
      dockerfile: dev.Dockerfile
    links:
      - be1:be1
    ports:
      - 4000:4000

  be1:
    build:
      context: ./be
      dockerfile: dev.Dockerfile
    ports:
      - 9081:9080
    volumes:
      - ./be/repo/src:/src
      - ./be/home:/home
