#!/bin/sh

cd fe
git clone https://github.com/freiny/dockerpack-fe-vm.git
mv ./dockerpack-fe-vm repo
cd ..

cd be
git clone https://github.com/freiny/dockerpack-be-vm.git
mv ./dockerpack-be-vm repo
cd ..
