#!/bin/sh
cd /src
# echo "OUTPUT: $bob"
# echo "$(node server.js)" >> /home/out.txt 2>&1



rm /home/out.txt
node server.js > /home/out.txt 2>&1
# cat /home/out.txt



# bob=$(node server.js)
# echo $bob
# $bob >> /home/out.txt
# cat /home/out.txt
# echo $bob && $bob >> outp ut.txt && cat output.txt
# npm install
# npm start &
#
# case $1 in
# 	dev)
# 		cd /src
# 		npm install
# 		npm start &
# 		ps -ef
# 		echo
#
# 		while inotifywait -e modify /src --recursive --exclude "npm-debug.log"; do
# 			killall -9 node
# 			npm start &
# 			ps ef
# 			echo
# 		done
# 	;;
#
# 	prod)
# 		cd /src
# 		npm install
# 		npm start
# 	;;
#
# 	*)
# 		echo "Init Container: init [dev | prod]"
#
# esac
