#!/bin/bash
ITAG=f-alpine:2
docker rmi $ITAG

BASE=alpine:3.4
docker pull $BASE

CMDS="
apk add --update bash
apk add --update nano
adduser -S dev
mkdir /home/dev && chown -R dev: /home/dev
chown -R dev: /home/dev
mkdir -p /home/dev/bin /home/dev/code /home/dev/go
PATH=$PATH:/home/dev/bin
cd /home/dev
HOME=/home/dev
GOPATH=/home/dev/go
chown -R dev: /home/dev
"

docker run --name cname $BASE sh -c "$CMDS"
cd home
docker cp . cname:home/dev
docker commit cname iname
docker rm cname

docker tag iname $ITAG
docker rmi iname
