#!/bin/bash

IMGNAME=f-alpine
IMGTAG=latest
IMGID=$IMGNAME:$IMGTAG

BASENAME=alpine
BASETAG=3.4
BASEID=$BASENAME:$BASETAG

echo "*********************************** START " $IMGID
docker rmi $IMGID
$FDOCKER/$BASENAME/$BASETAG/init
echo "*********************************** RUNNING " $IMGID
cd $FDOCKER/$IMGNAME/$IMGTAG
echo $IMGID " " $PWD

CMDS="
apk add --update bash
apk add --update nano
adduser -S dev
mkdir /home/dev && chown -R dev: /home/dev
chown -R dev: /home/dev
mkdir -p /home/dev/bin /home/dev/code /home/dev/go
PATH=$PATH:/home/dev/bin
chown -R dev: /home/dev
"

docker run --name cname $BASEID sh -c "$CMDS"
cd home
docker cp . cname:home/dev
cd ..
docker commit cname iname
docker rm cname

docker tag iname $IMGNAME
docker rmi iname

echo "*********************************** DONE " $IMGID
