#!/bin/sh

# USAGE: init [dev | prod]

imagePrefix=r1b3
githubRepo=dockerpack-be-nodejs
appContainer=be
githubUser=freiny

# Clear Containers
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -f "dangling=true" -q)

# Clear Images
docker rmi $(docker images -a -q)

docker rmi "$imagePrefix"_rp1:latest
docker rmi "$imagePrefix"_"$appContainer"1:latest
docker rmi "$imagePrefix"_"$appContainer"2:latest
docker rmi "$imagePrefix"_"$appContainer"3:latest

# Clean App
cd "$appContainer"
rm -rf repo
git clone https://github.com/"$githubUser"/"$githubRepo".git
mv ./"$githubRepo" repo
cd ..

docker-compose --file $1.yml up
