#!/bin/bash
BASE=f-alpine:1
ITAG=f-node:0

CMDS="apk add --update nodejs"

docker pull $BASE

docker run --name cname $BASE sh -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $ITAG
docker rmi iname
