#!/bin/bash

ITAG=f-go:0
docker rmi $ITAG

BASE=f-alpine:latest

CMDS="apk add --update git go"

docker run --name cname $BASE sh -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $ITAG
docker rmi iname
