#!/bin/sh

imagePrefix=vmback

# Stop Containers
docker stop "$imagePrefix"_rp1_1
docker stop "$imagePrefix"_ch1_1
docker stop "$imagePrefix"_be1_1
docker stop "$imagePrefix"_be2_1
docker stop "$imagePrefix"_be3_1
docker stop "$imagePrefix"_fe1_1
docker stop "$imagePrefix"_fe2_1
docker stop "$imagePrefix"_fe3_1

# Remove Containers
docker rm "$imagePrefix"_rp1_1
docker rm "$imagePrefix"_ch1_1
docker rm "$imagePrefix"_fe1_1
docker rm "$imagePrefix"_fe2_1
docker rm "$imagePrefix"_fe3_1
docker rm "$imagePrefix"_be1_1
docker rm "$imagePrefix"_be2_1
docker rm "$imagePrefix"_be3_1

# Remove Images
docker rmi "$imagePrefix"_rp1:latest
docker rmi "$imagePrefix"_ch1:latest
docker rmi "$imagePrefix"_fe1:latest
docker rmi "$imagePrefix"_fe2:latest
docker rmi "$imagePrefix"_fe3:latest
docker rmi "$imagePrefix"_be1:latest
docker rmi "$imagePrefix"_be2:latest
docker rmi "$imagePrefix"_be3:latest

rm -rf ./fe/repo
rm -rf ./be/repo
