#!/bin/bash
IMGID=f-node:latest
CNAME="fnodefe"

CODEPATH=$FDOCKER/f-node/examples/frontend/code

CMDS="cd /home/dev/code; npm install; npm start;"

docker run --name $CNAME -p 20080:20080 -v $CODEPATH:/home/dev/code --user="dev" -it $IMGID bash --login -c "$CMDS"
