#!/bin/bash
BASE=alpine:3.4
ITAG=f-alpine:0

CMDS="apk add --update bash"

docker pull $BASE

docker run --name cname $BASE sh -c "$CMDS"
docker commit cname iname
docker rm cname

docker tag iname $ITAG
docker rmi iname
